spring:
  application:
    name: spring-boot-data-redis-valkey-example
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  actuator:
    management:
      endpoints:
        web:
          exposure:
            include: "*"